"""empty message

Revision ID: 1a5ab99b7c75
Revises: 5f6accfc0e37
Create Date: 2023-06-07 14:36:56.119719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5ab99b7c75'
down_revision = '5f6accfc0e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'listings', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='unique')
    op.alter_column('listings', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###