"""empty message

Revision ID: 8a3e1819c05a
Revises: 5f6accfc0e37
Create Date: 2023-05-29 20:17:12.969450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3e1819c05a'
down_revision = '5f6accfc0e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageUrl', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['title'])
        batch_op.drop_column('image_url')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.String(length=2500),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('imageUrl')

    # ### end Alembic commands ###